# -*- coding: utf-8 -*-
"""Generador Inteligente de Descripciones de Producto con IA

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YzbNhupLIq7k2rh1KVsj_8-aGcALa5xe
"""

# Instalar librerías necesarias
!pip install transformers nltk gradio
import gradio as gr
from transformers import pipeline, set_seed
import nltk
from nltk.sentiment.vader import SentimentIntensityAnalyzer
nltk.download('vader_lexicon')

# Configuración inicial
generator = pipeline('text-generation', model='PlanTL-GOB-ES/gpt2-large-bne')  # Usando un modelo GPT-2 en español
set_seed(42)
sia = SentimentIntensityAnalyzer()

# Función que se conecta con la interfaz
def generar_descripciones(descripcion_base, longitud, opciones):
    resultados = generator(descripcion_base, max_length=longitud, num_return_sequences=opciones)
    respuestas = []

    for res in resultados:
        texto_crudo = res['generated_text']
        texto_limpio = texto_crudo.split(".")[0] + "."
        sentimiento = sia.polarity_scores(texto_limpio)

        if sentimiento['compound'] >= 0.05:
            estado = "💬 Sentimiento: Positivo ✅"
        elif sentimiento['compound'] <= -0.05:
            estado = "💬 Sentimiento: Negativo ❌"
        else:
            estado = "💬 Sentimiento: Neutral ⚪"

        respuestas.append(f"📄 {texto_limpio}\n{estado}")

    return "\n\n".join(respuestas)

# Crear la interfaz visual
interface = gr.Interface(
    fn=generar_descripciones,
    inputs=[
        gr.Textbox(label="✏️ Empieza tu descripción de producto", placeholder="Este difusor de aromas..."),
        gr.Slider(50, 200, step=10, label="📏 Longitud del texto"),
        gr.Slider(1, 5, step=1, label="🔁 Cantidad de versiones"),
    ],
    outputs=gr.Textbox(label="🧠 Descripciones generadas con IA"),
    title="Generador Inteligente de Descripciones de Producto",
    description="Introduce una idea y deja que la IA escriba por ti. Ideal para tiendas online, e-commerce, dropshipping y Amazon FBA."
)

# Lanzar la app
interface.launch()